/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BeerDetails {
        "beerId": string;
    }
    interface BeerList {
    }
    interface BeerListItem {
        "alcohol": number;
        "description": string;
        "id": string;
        "img": string;
        "name": string;
    }
    interface BeerMain {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBeerDetailsElement extends Components.BeerDetails, HTMLStencilElement {
    }
    var HTMLBeerDetailsElement: {
        prototype: HTMLBeerDetailsElement;
        new (): HTMLBeerDetailsElement;
    };
    interface HTMLBeerListElement extends Components.BeerList, HTMLStencilElement {
    }
    var HTMLBeerListElement: {
        prototype: HTMLBeerListElement;
        new (): HTMLBeerListElement;
    };
    interface HTMLBeerListItemElement extends Components.BeerListItem, HTMLStencilElement {
    }
    var HTMLBeerListItemElement: {
        prototype: HTMLBeerListItemElement;
        new (): HTMLBeerListItemElement;
    };
    interface HTMLBeerMainElement extends Components.BeerMain, HTMLStencilElement {
    }
    var HTMLBeerMainElement: {
        prototype: HTMLBeerMainElement;
        new (): HTMLBeerMainElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "beer-details": HTMLBeerDetailsElement;
        "beer-list": HTMLBeerListElement;
        "beer-list-item": HTMLBeerListItemElement;
        "beer-main": HTMLBeerMainElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BeerDetails {
        "beerId"?: string;
    }
    interface BeerList {
    }
    interface BeerListItem {
        "alcohol"?: number;
        "description"?: string;
        "id"?: string;
        "img"?: string;
        "name"?: string;
    }
    interface BeerMain {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "beer-details": BeerDetails;
        "beer-list": BeerList;
        "beer-list-item": BeerListItem;
        "beer-main": BeerMain;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "beer-details": LocalJSX.BeerDetails & JSXBase.HTMLAttributes<HTMLBeerDetailsElement>;
            "beer-list": LocalJSX.BeerList & JSXBase.HTMLAttributes<HTMLBeerListElement>;
            "beer-list-item": LocalJSX.BeerListItem & JSXBase.HTMLAttributes<HTMLBeerListItemElement>;
            "beer-main": LocalJSX.BeerMain & JSXBase.HTMLAttributes<HTMLBeerMainElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
