/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BeerList {
    }
    interface BeerListItem {
        "alcohol": number;
        "description": string;
        "name": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBeerListElement extends Components.BeerList, HTMLStencilElement {
    }
    var HTMLBeerListElement: {
        prototype: HTMLBeerListElement;
        new (): HTMLBeerListElement;
    };
    interface HTMLBeerListItemElement extends Components.BeerListItem, HTMLStencilElement {
    }
    var HTMLBeerListItemElement: {
        prototype: HTMLBeerListItemElement;
        new (): HTMLBeerListItemElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "beer-list": HTMLBeerListElement;
        "beer-list-item": HTMLBeerListItemElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BeerList {
    }
    interface BeerListItem {
        "alcohol"?: number;
        "description"?: string;
        "name"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "beer-list": BeerList;
        "beer-list-item": BeerListItem;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "beer-list": LocalJSX.BeerList & JSXBase.HTMLAttributes<HTMLBeerListElement>;
            "beer-list-item": LocalJSX.BeerListItem & JSXBase.HTMLAttributes<HTMLBeerListItemElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
